import {
  Clock,
  Database,
  FlaskConical,
  Gauge,
  Ruler,
  Square,
  Thermometer,
  Weight,
} from "lucide-react";

export const conversionCategories: Category[] = [
  {
    name: "Length",
    icon: Ruler,
    baseUnit: "meter",
    units: [
      { name: "Millimeter", symbol: "mm", ratio: 0.001 },
      { name: "Centimeter", symbol: "cm", ratio: 0.01 },
      { name: "Meter", symbol: "m", ratio: 1 },
      { name: "Kilometer", symbol: "km", ratio: 1000 },
      { name: "Inch", symbol: "in", ratio: 0.0254 },
      { name: "Foot", symbol: "ft", ratio: 0.3048 },
      { name: "Yard", symbol: "yd", ratio: 0.9144 },
      { name: "Mile", symbol: "mi", ratio: 1609.344 },
    ],
  },
  {
    name: "Mass",
    icon: Weight,
    baseUnit: "kilogram",
    units: [
      { name: "Milligram", symbol: "mg", ratio: 0.000001 },
      { name: "Gram", symbol: "g", ratio: 0.001 },
      { name: "Kilogram", symbol: "kg", ratio: 1 },
      { name: "Metric Ton", symbol: "t", ratio: 1000 },
      { name: "Ounce", symbol: "oz", ratio: 0.028349523125 },
      { name: "Pound", symbol: "lb", ratio: 0.45359237 },
      { name: "Stone", symbol: "st", ratio: 6.35029318 },
      { name: "US Ton", symbol: "ton", ratio: 907.18474 },
    ],
  },
  {
    name: "Temperature",
    icon: Thermometer,
    baseUnit: "celsius",
    units: [
      { name: "Celsius", symbol: "°C", ratio: 1 },
      { name: "Fahrenheit", symbol: "°F", ratio: 1 },
      { name: "Kelvin", symbol: "K", ratio: 1 },
    ],
  },
  {
    name: "Volume",
    icon: FlaskConical,
    baseUnit: "liter",
    units: [
      { name: "Milliliter", symbol: "ml", ratio: 0.001 },
      { name: "Centiliter", symbol: "cl", ratio: 0.01 },
      { name: "Liter", symbol: "l", ratio: 1 },
      { name: "Cubic meter", symbol: "m³", ratio: 1000 },
      { name: "US Fluid Ounce", symbol: "fl oz", ratio: 0.0295735295625 },
      { name: "US Cup", symbol: "cup", ratio: 0.2365882365 },
      { name: "US Pint", symbol: "pt", ratio: 0.473176473 },
      { name: "US Gallon", symbol: "gal", ratio: 3.785411784 },
    ],
  },
  {
    name: "Area",
    icon: Square,
    baseUnit: "square meter",
    units: [
      { name: "Square Millimeter", symbol: "mm²", ratio: 0.000001 },
      { name: "Square Centimeter", symbol: "cm²", ratio: 0.0001 },
      { name: "Square Meter", symbol: "m²", ratio: 1 },
      { name: "Hectare", symbol: "ha", ratio: 10000 },
      { name: "Square Kilometer", symbol: "km²", ratio: 1000000 },
      { name: "Square Inch", symbol: "in²", ratio: 0.00064516 },
      { name: "Square Foot", symbol: "ft²", ratio: 0.09290304 },
      { name: "Acre", symbol: "ac", ratio: 4046.8564224 },
      { name: "Square Mile", symbol: "mi²", ratio: 2589988.110336 },
    ],
  },
  {
    name: "Speed",
    icon: Gauge,
    baseUnit: "meter per second",
    units: [
      { name: "Meter per second", symbol: "m/s", ratio: 1 },
      { name: "Kilometer per hour", symbol: "km/h", ratio: 0.277777778 },
      { name: "Mile per hour", symbol: "mph", ratio: 0.44704 },
      { name: "Knot", symbol: "kn", ratio: 0.514444444 },
      { name: "Foot per second", symbol: "ft/s", ratio: 0.3048 },
    ],
  },
  {
    name: "Time",
    icon: Clock,
    baseUnit: "second",
    units: [
      { name: "Millisecond", symbol: "ms", ratio: 0.001 },
      { name: "Second", symbol: "s", ratio: 1 },
      { name: "Minute", symbol: "min", ratio: 60 },
      { name: "Hour", symbol: "h", ratio: 3600 },
      { name: "Day", symbol: "d", ratio: 86400 },
      { name: "Week", symbol: "wk", ratio: 604800 },
      { name: "Month (30 days)", symbol: "mo", ratio: 2592000 },
      { name: "Year (365 days)", symbol: "yr", ratio: 31536000 },
    ],
  },
  {
    name: "Data",
    icon: Database,
    baseUnit: "byte",
    units: [
      { name: "Bit", symbol: "bit", ratio: 0.125 },
      { name: "Byte", symbol: "B", ratio: 1 },
      { name: "Kilobyte", symbol: "KB", ratio: 1024 },
      { name: "Megabyte", symbol: "MB", ratio: 1048576 },
      { name: "Gigabyte", symbol: "GB", ratio: 1073741824 },
      { name: "Terabyte", symbol: "TB", ratio: 1099511627776 },
    ],
  },
];
